commands:
  create:
    name: create
    description: "Creates profile for user in repository. Profile name has to unique"
    args: [user, project, name]
  get:
    name: get
    args: [name]
    description: "shows user and repository for profile"
  list:
    name: list
    description: "shows list of all profiles"
  delete:
    args: [name]
    description: "deletes profile"

args:
  user:
    shortName: u
    description: name of user
  name:
    shortName: n
    description: unique name of profile
  project:
    shortName: p
    description: name of project

