// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "CloudCLI/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryInterface is an autogenerated mock type for the RepositoryInterface type
type RepositoryInterface struct {
	mock.Mock
}

// ProfileCreate provides a mock function with given fields: user, name, project
func (_m *RepositoryInterface) ProfileCreate(user string, name string, project string) error {
	ret := _m.Called(user, name, project)

	if len(ret) == 0 {
		panic("no return value specified for ProfileCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(user, name, project)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProfileDelete provides a mock function with given fields: name
func (_m *RepositoryInterface) ProfileDelete(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ProfileDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProfileGet provides a mock function with given fields: name
func (_m *RepositoryInterface) ProfileGet(name string) (*models.Profile, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ProfileGet")
	}

	var r0 *models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Profile, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Profile); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfileList provides a mock function with no fields
func (_m *RepositoryInterface) ProfileList() (map[string]*models.Profile, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProfileList")
	}

	var r0 map[string]*models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]*models.Profile, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]*models.Profile); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepositoryInterface creates a new instance of RepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryInterface {
	mock := &RepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
