// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ServiceInterface is an autogenerated mock type for the ServiceInterface type
type ServiceInterface struct {
	mock.Mock
}

// ProfileCreate provides a mock function with given fields: args
func (_m *ServiceInterface) ProfileCreate(args map[string]string) error {
	ret := _m.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for ProfileCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = rf(args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProfileDelete provides a mock function with given fields: args
func (_m *ServiceInterface) ProfileDelete(args map[string]string) error {
	ret := _m.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for ProfileDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = rf(args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProfileGet provides a mock function with given fields: args
func (_m *ServiceInterface) ProfileGet(args map[string]string) error {
	ret := _m.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for ProfileGet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = rf(args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProfileList provides a mock function with given fields: args
func (_m *ServiceInterface) ProfileList(args map[string]string) error {
	ret := _m.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for ProfileList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = rf(args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServiceInterface creates a new instance of ServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceInterface {
	mock := &ServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
